import React, { useEffect, useState } from 'react';
import { useAuth } from '../context/AuthContext';
import api from '../utils/api';
import toast from 'react-hot-toast';
import { exportCSV } from '../utils/attendance';

export default function Profile() {
  const { user } = useAuth();
  const [subjects, setSubjects] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    api.get('/subjects')
      .then(({ data }) => setSubjects(data.subjects || []))
      .catch(() => {})
      .finally(() => setLoading(false));
  }, []);

  const joinedDate = user?.createdAt
    ? new Date(user.createdAt).toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' })
    : 'N/A';

  const overall = subjects.length > 0
    ? (subjects.reduce((s, sub) => s + sub.attendancePercentage, 0) / subjects.length).toFixed(1)
    : '—';

  const handleExportCSV = () => {
    if (subjects.length === 0) { toast.error('No subjects to export'); return; }
    exportCSV(subjects, user?.name || 'student');
    toast.success('CSV downloaded!');
  };

  const handleExportPDF = async () => {
    if (subjects.length === 0) { toast.error('No subjects to export'); return; }
    try {
      const { default: jsPDF } = await import('jspdf');
      const { default: autoTable } = await import('jspdf-autotable');
      const doc = new jsPDF();

      // Header
      doc.setFillColor(109, 93, 252);
      doc.rect(0, 0, 210, 40, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(22);
      doc.setFont('helvetica', 'bold');
      doc.text('AttendWise AI', 14, 18);
      doc.setFontSize(11);
      doc.setFont('helvetica', 'normal');
      doc.text('Attendance Report', 14, 28);
      doc.text(new Date().toLocaleDateString('en-IN', { dateStyle: 'full' }), 14, 36);

      // Student Info
      doc.setTextColor(51, 65, 85);
      doc.setFontSize(13);
      doc.setFont('helvetica', 'bold');
      doc.text('Student Information', 14, 56);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(11);
      doc.text(`Name: ${user?.name || 'N/A'}`, 14, 66);
      doc.text(`Email: ${user?.email || 'N/A'}`, 14, 74);
      doc.text(`Overall Attendance: ${overall}%`, 14, 82);
      doc.text(`Total Subjects: ${subjects.length}`, 14, 90);

      // Table
      autoTable(doc, {
        startY: 102,
        head: [['Subject', 'Attended', 'Total', 'Percentage', 'Status']],
        body: subjects.map(s => [
          s.subjectName,
          s.attendedClasses,
          s.totalClasses,
          `${s.attendancePercentage}%`,
          s.attendancePercentage >= 80 ? 'SAFE' : s.attendancePercentage >= 75 ? 'WARNING' : 'CRITICAL',
        ]),
        headStyles: { fillColor: [109, 93, 252], textColor: [255, 255, 255], fontStyle: 'bold' },
        bodyStyles: { textColor: [51, 65, 85] },
        alternateRowStyles: { fillColor: [248, 250, 252] },
        didDrawCell: (data) => {
          if (data.section === 'body' && data.column.index === 4) {
            const val = data.cell.raw;
            const color = val === 'SAFE' ? [16, 185, 129] : val === 'WARNING' ? [245, 158, 11] : [239, 68, 68];
            doc.setTextColor(...color);
            doc.setFont('helvetica', 'bold');
            doc.text(val, data.cell.x + 2, data.cell.y + 6);
            doc.setFont('helvetica', 'normal');
            doc.setTextColor(51, 65, 85);
          }
        },
      });

      // Footer
      const pageCount = doc.internal.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(9);
        doc.setTextColor(148, 163, 184);
        doc.text('Generated by AttendWise AI', 14, 285);
        doc.text(`Page ${i} of ${pageCount}`, 180, 285);
      }

      doc.save(`attendwise_report_${user?.name?.replace(/\s+/g, '_') || 'student'}_${new Date().toISOString().split('T')[0]}.pdf`);
      toast.success('PDF report downloaded!');
    } catch (err) {
      console.error(err);
      toast.error('Failed to generate PDF');
    }
  };

  return (
    <div className="max-w-2xl mx-auto space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-slate-800 dark:text-white">👤 Profile</h1>
        <p className="text-slate-500 dark:text-slate-400 text-sm mt-0.5">Your account information and reports</p>
      </div>

      {/* Profile Card */}
      <div className="glass-card p-8">
        <div className="flex items-center gap-5 mb-6">
          <div className="w-20 h-20 bg-gradient-to-br from-primary-500 to-accent rounded-2xl flex items-center justify-center text-white text-3xl font-bold shadow-glass">
            {user?.name?.charAt(0).toUpperCase()}
          </div>
          <div>
            <h2 className="text-xl font-bold text-slate-800 dark:text-white">{user?.name}</h2>
            <p className="text-slate-500 dark:text-slate-400 text-sm">{user?.email}</p>
            <span className="mt-1.5 inline-block text-xs bg-primary-50 dark:bg-primary-900/30 text-primary-600 dark:text-primary-400 px-3 py-1 rounded-full border border-primary-100 dark:border-primary-800 font-medium">
              🎓 Student
            </span>
          </div>
        </div>

        <div className="grid grid-cols-2 gap-4">
          {[
            { label: 'Member Since', value: joinedDate, icon: '📅' },
            { label: 'Total Subjects', value: subjects.length, icon: '📚' },
            { label: 'Overall Attendance', value: `${overall}%`, icon: '📊' },
            { label: 'Safe Subjects', value: subjects.filter(s => s.attendancePercentage >= 80).length, icon: '✅' },
          ].map(item => (
            <div key={item.label} className="bg-slate-50 dark:bg-slate-700/50 rounded-xl p-4">
              <span className="text-xl">{item.icon}</span>
              <p className="text-xs text-slate-500 dark:text-slate-400 mt-2 font-medium">{item.label}</p>
              <p className="text-lg font-bold text-slate-800 dark:text-white mt-0.5">{item.value}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Export Options */}
      <div className="glass-card p-6">
        <h3 className="font-semibold text-slate-800 dark:text-white mb-4">📄 Export Reports</h3>
        <div className="grid grid-cols-2 gap-4">
          <button
            onClick={handleExportCSV}
            className="flex items-center gap-3 p-4 rounded-xl border border-slate-200 dark:border-slate-600 hover:border-primary-300 dark:hover:border-primary-600 hover:bg-primary-50 dark:hover:bg-primary-900/20 transition-all group"
          >
            <span className="text-2xl">📊</span>
            <div className="text-left">
              <p className="font-semibold text-slate-700 dark:text-slate-300 text-sm group-hover:text-primary-600 dark:group-hover:text-primary-400 transition-colors">Export CSV</p>
              <p className="text-xs text-slate-400">Spreadsheet format</p>
            </div>
          </button>
          <button
            onClick={handleExportPDF}
            className="flex items-center gap-3 p-4 rounded-xl border border-slate-200 dark:border-slate-600 hover:border-primary-300 dark:hover:border-primary-600 hover:bg-primary-50 dark:hover:bg-primary-900/20 transition-all group"
          >
            <span className="text-2xl">📄</span>
            <div className="text-left">
              <p className="font-semibold text-slate-700 dark:text-slate-300 text-sm group-hover:text-primary-600 dark:group-hover:text-primary-400 transition-colors">Export PDF</p>
              <p className="text-xs text-slate-400">Formatted report</p>
            </div>
          </button>
        </div>
      </div>

      {/* Subject Summary */}
      {subjects.length > 0 && (
        <div className="glass-card p-6">
          <h3 className="font-semibold text-slate-800 dark:text-white mb-4">📚 Subject Summary</h3>
          <div className="space-y-3">
            {subjects.map(s => (
              <div key={s._id} className="flex items-center gap-3">
                <div className="flex-1">
                  <div className="flex justify-between text-sm mb-1">
                    <span className="font-medium text-slate-700 dark:text-slate-300">{s.subjectName}</span>
                    <span className={`font-bold ${s.attendancePercentage >= 80 ? 'text-emerald-600' : s.attendancePercentage >= 75 ? 'text-amber-600' : 'text-red-600'}`}>
                      {s.attendancePercentage}%
                    </span>
                  </div>
                  <div className="h-1.5 bg-slate-100 dark:bg-slate-700 rounded-full overflow-hidden">
                    <div
                      className="h-full rounded-full progress-bar"
                      style={{
                        width: `${Math.min(100, s.attendancePercentage)}%`,
                        background: s.attendancePercentage >= 80 ? '#10B981' : s.attendancePercentage >= 75 ? '#F59E0B' : '#EF4444',
                      }}
                    />
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
